# -*- encoding: utf-8 -*-

=begin
#Blockmate

#Blockmate API OpenAPI documentation

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "blockmate/version"

Gem::Specification.new do |s|
  s.name        = "blockmate"
  s.version     = Blockmate::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Blockmate Ruby Gem"
  s.description = "Blockmate API OpenAPI documentation"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7.1"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
