=begin
#Blockmate

#Blockmate API OpenAPI documentation

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module Blockmate
  class Analytics1
    # Sum of all transactions
    attr_accessor :sum_txs_all_forever_onchain

    # Sum of all NFT transactions
    attr_accessor :sum_txs_all_forever_nft

    # Sum of all gaming transactions
    attr_accessor :sum_txs_all_forever_gaming

    # Sum of all gambling transactions
    attr_accessor :sum_txs_all_forever_gambling

    # Sum of all transactions during last year
    attr_accessor :sum_txs_all_365_onchain

    # Sum of all NFT transactions during last year
    attr_accessor :sum_txs_all_365_nft

    # Sum of all gaming transactions during last year
    attr_accessor :sum_txs_all_365_gaming

    # Sum of all gambling transactions during last year
    attr_accessor :sum_txs_all_365_gambling

    # Sum of all transactions during previous month
    attr_accessor :sum_txs_all_31_60_onchain

    # Sum of all NFT transactions during previous month
    attr_accessor :sum_txs_all_31_60_nft

    # Sum of all gaming transactions during previous month
    attr_accessor :sum_txs_all_31_60_gaming

    # Sum of all gambling transactions during previous month
    attr_accessor :sum_txs_all_31_60_gambling

    # Sum of all transactions during last month
    attr_accessor :sum_txs_all_30_onchain

    # Sum of all NFT transactions during last month
    attr_accessor :sum_txs_all_30_nft

    # Sum of all gaming transactions during last month
    attr_accessor :sum_txs_all_30_gaming

    # Sum of all gambling transactions during last month
    attr_accessor :sum_txs_all_30_gambling

    # Sum of all transactions during last week
    attr_accessor :sum_txs_all_7_onchain

    # Sum of all NFT transactions during last week
    attr_accessor :sum_txs_all_7_nft

    # Sum of all gaming transactions during last week
    attr_accessor :sum_txs_all_7_gaming

    # Sum of all gambling transactions during last week
    attr_accessor :sum_txs_all_7_gambling

    # Sum of all IN transactions
    attr_accessor :sum_txs_in_forever_onchain

    # Sum of all IN NFT transactions
    attr_accessor :sum_txs_in_forever_nft

    # Sum of all IN gaming transactions
    attr_accessor :sum_txs_in_forever_gaming

    # Sum of all IN gambling transactions
    attr_accessor :sum_txs_in_forever_gambling

    # Sum of all IN transactions during last year
    attr_accessor :sum_txs_in_365_onchain

    # Sum of all IN NFT transactions during last year
    attr_accessor :sum_txs_in_365_nft

    # Sum of all IN gaming transactions during last year
    attr_accessor :sum_txs_in_365_gaming

    # Sum of all IN gambling transactions during last year
    attr_accessor :sum_txs_in_365_gambling

    # Sum of all IN transactions during previous month
    attr_accessor :sum_txs_in_31_60_onchain

    # Sum of all IN NFT transactions during previous month
    attr_accessor :sum_txs_in_31_60_nft

    # Sum of all IN gaming transactions during previous month
    attr_accessor :sum_txs_in_31_60_gaming

    # Sum of all IN gambling transactions during previous month
    attr_accessor :sum_txs_in_31_60_gambling

    # Sum of all IN transactions during last month
    attr_accessor :sum_txs_in_30_onchain

    # Sum of all IN NFT transactions during last month
    attr_accessor :sum_txs_in_30_nft

    # Sum of all IN gaming transactions during last month
    attr_accessor :sum_txs_in_30_gaming

    # Sum of all IN gambling transactions during last month
    attr_accessor :sum_txs_in_30_gambling

    # Sum of all IN transactions during last week
    attr_accessor :sum_txs_in_7_onchain

    # Sum of all IN NFT transactions during last week
    attr_accessor :sum_txs_in_7_nft

    # Sum of all IN gaming transactions during last week
    attr_accessor :sum_txs_in_7_gaming

    # Sum of all IN gambling transactions during last week
    attr_accessor :sum_txs_in_7_gambling

    # Sum of all OUT transactions
    attr_accessor :sum_txs_out_forever_onchain

    # Sum of all OUT NFT transactions
    attr_accessor :sum_txs_out_forever_nft

    # Sum of all OUT gaming transactions
    attr_accessor :sum_txs_out_forever_gaming

    # Sum of all OUT gambling transactions
    attr_accessor :sum_txs_out_forever_gambling

    # Sum of all OUT transactions during last year
    attr_accessor :sum_txs_out_365_onchain

    # Sum of all OUT NFT transactions during last year
    attr_accessor :sum_txs_out_365_nft

    # Sum of all OUT gaming transactions during last year
    attr_accessor :sum_txs_out_365_gaming

    # Sum of all OUT gambling transactions during last year
    attr_accessor :sum_txs_out_365_gambling

    # Sum of all OUT transactions during previous month
    attr_accessor :sum_txs_out_31_60_onchain

    # Sum of all OUT NFT transactions during previous month
    attr_accessor :sum_txs_out_31_60_nft

    # Sum of all OUT gaming transactions during previous month
    attr_accessor :sum_txs_out_31_60_gaming

    # Sum of all OUT gambling transactions during previous month
    attr_accessor :sum_txs_out_31_60_gambling

    # Sum of all OUT transactions during last month
    attr_accessor :sum_txs_out_30_onchain

    # Sum of all OUT NFT transactions during last month
    attr_accessor :sum_txs_out_30_nft

    # Sum of all OUT gaming transactions during last month
    attr_accessor :sum_txs_out_30_gaming

    # Sum of all OUT gambling transactions during last month
    attr_accessor :sum_txs_out_30_gambling

    # Sum of all OUT transactions during last week
    attr_accessor :sum_txs_out_7_onchain

    # Sum of all OUT NFT transactions during last week
    attr_accessor :sum_txs_out_7_nft

    # Sum of all OUT gaming transactions during last week
    attr_accessor :sum_txs_out_7_gaming

    # Sum of all OUT gambling transactions during last week
    attr_accessor :sum_txs_out_7_gambling

    # Maximum balance
    attr_accessor :max_balance_forever_onchain

    # Maximum NFT balance
    attr_accessor :max_balance_forever_nft

    # Maximum gaming balance
    attr_accessor :max_balance_forever_gaming

    # Maximum gambing balance
    attr_accessor :max_balance_forever_gambling

    # Maximum balance during last year
    attr_accessor :max_balance_365_onchain

    # Maximum NFT balance during last year
    attr_accessor :max_balance_365_nft

    # Maximum gaming balance during last year
    attr_accessor :max_balance_365_gaming

    # Maximum gambling balance during last year
    attr_accessor :max_balance_365_gambling

    # Maximum balance during previous month
    attr_accessor :max_balance_31_60_onchain

    # Maximum NFT balance during previous month
    attr_accessor :max_balance_31_60_nft

    # Maximum gaming balance during previous month
    attr_accessor :max_balance_31_60_gaming

    # Maximum gambling balance during previous month
    attr_accessor :max_balance_31_60_gambling

    # Maximum balance during last month
    attr_accessor :max_balance_30_onchain

    # Maximum NFT balance during last month
    attr_accessor :max_balance_30_nft

    # Maximum gaming balance during last month
    attr_accessor :max_balance_30_gaming

    # Maximum gambling balance during last month
    attr_accessor :max_balance_30_gambling

    # Maximum balance during last week
    attr_accessor :max_balance_7_onchain

    # Maximum NFT balance during last week
    attr_accessor :max_balance_7_nft

    # Maximum gaming balance during last week
    attr_accessor :max_balance_7_gaming

    # Maximum gambling balance during last week
    attr_accessor :max_balance_7_gambling

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sum_txs_all_forever_onchain' => :'sum_txs_all_forever_onchain',
        :'sum_txs_all_forever_nft' => :'sum_txs_all_forever_nft',
        :'sum_txs_all_forever_gaming' => :'sum_txs_all_forever_gaming',
        :'sum_txs_all_forever_gambling' => :'sum_txs_all_forever_gambling',
        :'sum_txs_all_365_onchain' => :'sum_txs_all_365_onchain',
        :'sum_txs_all_365_nft' => :'sum_txs_all_365_nft',
        :'sum_txs_all_365_gaming' => :'sum_txs_all_365_gaming',
        :'sum_txs_all_365_gambling' => :'sum_txs_all_365_gambling',
        :'sum_txs_all_31_60_onchain' => :'sum_txs_all_31_60_onchain',
        :'sum_txs_all_31_60_nft' => :'sum_txs_all_31_60_nft',
        :'sum_txs_all_31_60_gaming' => :'sum_txs_all_31_60_gaming',
        :'sum_txs_all_31_60_gambling' => :'sum_txs_all_31_60_gambling',
        :'sum_txs_all_30_onchain' => :'sum_txs_all_30_onchain',
        :'sum_txs_all_30_nft' => :'sum_txs_all_30_nft',
        :'sum_txs_all_30_gaming' => :'sum_txs_all_30_gaming',
        :'sum_txs_all_30_gambling' => :'sum_txs_all_30_gambling',
        :'sum_txs_all_7_onchain' => :'sum_txs_all_7_onchain',
        :'sum_txs_all_7_nft' => :'sum_txs_all_7_nft',
        :'sum_txs_all_7_gaming' => :'sum_txs_all_7_gaming',
        :'sum_txs_all_7_gambling' => :'sum_txs_all_7_gambling',
        :'sum_txs_in_forever_onchain' => :'sum_txs_in_forever_onchain',
        :'sum_txs_in_forever_nft' => :'sum_txs_in_forever_nft',
        :'sum_txs_in_forever_gaming' => :'sum_txs_in_forever_gaming',
        :'sum_txs_in_forever_gambling' => :'sum_txs_in_forever_gambling',
        :'sum_txs_in_365_onchain' => :'sum_txs_in_365_onchain',
        :'sum_txs_in_365_nft' => :'sum_txs_in_365_nft',
        :'sum_txs_in_365_gaming' => :'sum_txs_in_365_gaming',
        :'sum_txs_in_365_gambling' => :'sum_txs_in_365_gambling',
        :'sum_txs_in_31_60_onchain' => :'sum_txs_in_31_60_onchain',
        :'sum_txs_in_31_60_nft' => :'sum_txs_in_31_60_nft',
        :'sum_txs_in_31_60_gaming' => :'sum_txs_in_31_60_gaming',
        :'sum_txs_in_31_60_gambling' => :'sum_txs_in_31_60_gambling',
        :'sum_txs_in_30_onchain' => :'sum_txs_in_30_onchain',
        :'sum_txs_in_30_nft' => :'sum_txs_in_30_nft',
        :'sum_txs_in_30_gaming' => :'sum_txs_in_30_gaming',
        :'sum_txs_in_30_gambling' => :'sum_txs_in_30_gambling',
        :'sum_txs_in_7_onchain' => :'sum_txs_in_7_onchain',
        :'sum_txs_in_7_nft' => :'sum_txs_in_7_nft',
        :'sum_txs_in_7_gaming' => :'sum_txs_in_7_gaming',
        :'sum_txs_in_7_gambling' => :'sum_txs_in_7_gambling',
        :'sum_txs_out_forever_onchain' => :'sum_txs_out_forever_onchain',
        :'sum_txs_out_forever_nft' => :'sum_txs_out_forever_nft',
        :'sum_txs_out_forever_gaming' => :'sum_txs_out_forever_gaming',
        :'sum_txs_out_forever_gambling' => :'sum_txs_out_forever_gambling',
        :'sum_txs_out_365_onchain' => :'sum_txs_out_365_onchain',
        :'sum_txs_out_365_nft' => :'sum_txs_out_365_nft',
        :'sum_txs_out_365_gaming' => :'sum_txs_out_365_gaming',
        :'sum_txs_out_365_gambling' => :'sum_txs_out_365_gambling',
        :'sum_txs_out_31_60_onchain' => :'sum_txs_out_31_60_onchain',
        :'sum_txs_out_31_60_nft' => :'sum_txs_out_31_60_nft',
        :'sum_txs_out_31_60_gaming' => :'sum_txs_out_31_60_gaming',
        :'sum_txs_out_31_60_gambling' => :'sum_txs_out_31_60_gambling',
        :'sum_txs_out_30_onchain' => :'sum_txs_out_30_onchain',
        :'sum_txs_out_30_nft' => :'sum_txs_out_30_nft',
        :'sum_txs_out_30_gaming' => :'sum_txs_out_30_gaming',
        :'sum_txs_out_30_gambling' => :'sum_txs_out_30_gambling',
        :'sum_txs_out_7_onchain' => :'sum_txs_out_7_onchain',
        :'sum_txs_out_7_nft' => :'sum_txs_out_7_nft',
        :'sum_txs_out_7_gaming' => :'sum_txs_out_7_gaming',
        :'sum_txs_out_7_gambling' => :'sum_txs_out_7_gambling',
        :'max_balance_forever_onchain' => :'max_balance_forever_onchain',
        :'max_balance_forever_nft' => :'max_balance_forever_nft',
        :'max_balance_forever_gaming' => :'max_balance_forever_gaming',
        :'max_balance_forever_gambling' => :'max_balance_forever_gambling',
        :'max_balance_365_onchain' => :'max_balance_365_onchain',
        :'max_balance_365_nft' => :'max_balance_365_nft',
        :'max_balance_365_gaming' => :'max_balance_365_gaming',
        :'max_balance_365_gambling' => :'max_balance_365_gambling',
        :'max_balance_31_60_onchain' => :'max_balance_31_60_onchain',
        :'max_balance_31_60_nft' => :'max_balance_31_60_nft',
        :'max_balance_31_60_gaming' => :'max_balance_31_60_gaming',
        :'max_balance_31_60_gambling' => :'max_balance_31_60_gambling',
        :'max_balance_30_onchain' => :'max_balance_30_onchain',
        :'max_balance_30_nft' => :'max_balance_30_nft',
        :'max_balance_30_gaming' => :'max_balance_30_gaming',
        :'max_balance_30_gambling' => :'max_balance_30_gambling',
        :'max_balance_7_onchain' => :'max_balance_7_onchain',
        :'max_balance_7_nft' => :'max_balance_7_nft',
        :'max_balance_7_gaming' => :'max_balance_7_gaming',
        :'max_balance_7_gambling' => :'max_balance_7_gambling'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sum_txs_all_forever_onchain' => :'Float',
        :'sum_txs_all_forever_nft' => :'Float',
        :'sum_txs_all_forever_gaming' => :'Float',
        :'sum_txs_all_forever_gambling' => :'Float',
        :'sum_txs_all_365_onchain' => :'Float',
        :'sum_txs_all_365_nft' => :'Float',
        :'sum_txs_all_365_gaming' => :'Float',
        :'sum_txs_all_365_gambling' => :'Float',
        :'sum_txs_all_31_60_onchain' => :'Float',
        :'sum_txs_all_31_60_nft' => :'Float',
        :'sum_txs_all_31_60_gaming' => :'Float',
        :'sum_txs_all_31_60_gambling' => :'Float',
        :'sum_txs_all_30_onchain' => :'Float',
        :'sum_txs_all_30_nft' => :'Float',
        :'sum_txs_all_30_gaming' => :'Float',
        :'sum_txs_all_30_gambling' => :'Float',
        :'sum_txs_all_7_onchain' => :'Float',
        :'sum_txs_all_7_nft' => :'Float',
        :'sum_txs_all_7_gaming' => :'Float',
        :'sum_txs_all_7_gambling' => :'Float',
        :'sum_txs_in_forever_onchain' => :'Float',
        :'sum_txs_in_forever_nft' => :'Float',
        :'sum_txs_in_forever_gaming' => :'Float',
        :'sum_txs_in_forever_gambling' => :'Float',
        :'sum_txs_in_365_onchain' => :'Float',
        :'sum_txs_in_365_nft' => :'Float',
        :'sum_txs_in_365_gaming' => :'Float',
        :'sum_txs_in_365_gambling' => :'Float',
        :'sum_txs_in_31_60_onchain' => :'Float',
        :'sum_txs_in_31_60_nft' => :'Float',
        :'sum_txs_in_31_60_gaming' => :'Float',
        :'sum_txs_in_31_60_gambling' => :'Float',
        :'sum_txs_in_30_onchain' => :'Float',
        :'sum_txs_in_30_nft' => :'Float',
        :'sum_txs_in_30_gaming' => :'Float',
        :'sum_txs_in_30_gambling' => :'Float',
        :'sum_txs_in_7_onchain' => :'Float',
        :'sum_txs_in_7_nft' => :'Float',
        :'sum_txs_in_7_gaming' => :'Float',
        :'sum_txs_in_7_gambling' => :'Float',
        :'sum_txs_out_forever_onchain' => :'Float',
        :'sum_txs_out_forever_nft' => :'Float',
        :'sum_txs_out_forever_gaming' => :'Float',
        :'sum_txs_out_forever_gambling' => :'Float',
        :'sum_txs_out_365_onchain' => :'Float',
        :'sum_txs_out_365_nft' => :'Float',
        :'sum_txs_out_365_gaming' => :'Float',
        :'sum_txs_out_365_gambling' => :'Float',
        :'sum_txs_out_31_60_onchain' => :'Float',
        :'sum_txs_out_31_60_nft' => :'Float',
        :'sum_txs_out_31_60_gaming' => :'Float',
        :'sum_txs_out_31_60_gambling' => :'Float',
        :'sum_txs_out_30_onchain' => :'Float',
        :'sum_txs_out_30_nft' => :'Float',
        :'sum_txs_out_30_gaming' => :'Float',
        :'sum_txs_out_30_gambling' => :'Float',
        :'sum_txs_out_7_onchain' => :'Float',
        :'sum_txs_out_7_nft' => :'Float',
        :'sum_txs_out_7_gaming' => :'Float',
        :'sum_txs_out_7_gambling' => :'Float',
        :'max_balance_forever_onchain' => :'Float',
        :'max_balance_forever_nft' => :'Float',
        :'max_balance_forever_gaming' => :'Float',
        :'max_balance_forever_gambling' => :'Float',
        :'max_balance_365_onchain' => :'Float',
        :'max_balance_365_nft' => :'Float',
        :'max_balance_365_gaming' => :'Float',
        :'max_balance_365_gambling' => :'Float',
        :'max_balance_31_60_onchain' => :'Float',
        :'max_balance_31_60_nft' => :'Float',
        :'max_balance_31_60_gaming' => :'Float',
        :'max_balance_31_60_gambling' => :'Float',
        :'max_balance_30_onchain' => :'Float',
        :'max_balance_30_nft' => :'Float',
        :'max_balance_30_gaming' => :'Float',
        :'max_balance_30_gambling' => :'Float',
        :'max_balance_7_onchain' => :'Float',
        :'max_balance_7_nft' => :'Float',
        :'max_balance_7_gaming' => :'Float',
        :'max_balance_7_gambling' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Blockmate::Analytics1` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Blockmate::Analytics1`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sum_txs_all_forever_onchain')
        self.sum_txs_all_forever_onchain = attributes[:'sum_txs_all_forever_onchain']
      end

      if attributes.key?(:'sum_txs_all_forever_nft')
        self.sum_txs_all_forever_nft = attributes[:'sum_txs_all_forever_nft']
      end

      if attributes.key?(:'sum_txs_all_forever_gaming')
        self.sum_txs_all_forever_gaming = attributes[:'sum_txs_all_forever_gaming']
      end

      if attributes.key?(:'sum_txs_all_forever_gambling')
        self.sum_txs_all_forever_gambling = attributes[:'sum_txs_all_forever_gambling']
      end

      if attributes.key?(:'sum_txs_all_365_onchain')
        self.sum_txs_all_365_onchain = attributes[:'sum_txs_all_365_onchain']
      end

      if attributes.key?(:'sum_txs_all_365_nft')
        self.sum_txs_all_365_nft = attributes[:'sum_txs_all_365_nft']
      end

      if attributes.key?(:'sum_txs_all_365_gaming')
        self.sum_txs_all_365_gaming = attributes[:'sum_txs_all_365_gaming']
      end

      if attributes.key?(:'sum_txs_all_365_gambling')
        self.sum_txs_all_365_gambling = attributes[:'sum_txs_all_365_gambling']
      end

      if attributes.key?(:'sum_txs_all_31_60_onchain')
        self.sum_txs_all_31_60_onchain = attributes[:'sum_txs_all_31_60_onchain']
      end

      if attributes.key?(:'sum_txs_all_31_60_nft')
        self.sum_txs_all_31_60_nft = attributes[:'sum_txs_all_31_60_nft']
      end

      if attributes.key?(:'sum_txs_all_31_60_gaming')
        self.sum_txs_all_31_60_gaming = attributes[:'sum_txs_all_31_60_gaming']
      end

      if attributes.key?(:'sum_txs_all_31_60_gambling')
        self.sum_txs_all_31_60_gambling = attributes[:'sum_txs_all_31_60_gambling']
      end

      if attributes.key?(:'sum_txs_all_30_onchain')
        self.sum_txs_all_30_onchain = attributes[:'sum_txs_all_30_onchain']
      end

      if attributes.key?(:'sum_txs_all_30_nft')
        self.sum_txs_all_30_nft = attributes[:'sum_txs_all_30_nft']
      end

      if attributes.key?(:'sum_txs_all_30_gaming')
        self.sum_txs_all_30_gaming = attributes[:'sum_txs_all_30_gaming']
      end

      if attributes.key?(:'sum_txs_all_30_gambling')
        self.sum_txs_all_30_gambling = attributes[:'sum_txs_all_30_gambling']
      end

      if attributes.key?(:'sum_txs_all_7_onchain')
        self.sum_txs_all_7_onchain = attributes[:'sum_txs_all_7_onchain']
      end

      if attributes.key?(:'sum_txs_all_7_nft')
        self.sum_txs_all_7_nft = attributes[:'sum_txs_all_7_nft']
      end

      if attributes.key?(:'sum_txs_all_7_gaming')
        self.sum_txs_all_7_gaming = attributes[:'sum_txs_all_7_gaming']
      end

      if attributes.key?(:'sum_txs_all_7_gambling')
        self.sum_txs_all_7_gambling = attributes[:'sum_txs_all_7_gambling']
      end

      if attributes.key?(:'sum_txs_in_forever_onchain')
        self.sum_txs_in_forever_onchain = attributes[:'sum_txs_in_forever_onchain']
      end

      if attributes.key?(:'sum_txs_in_forever_nft')
        self.sum_txs_in_forever_nft = attributes[:'sum_txs_in_forever_nft']
      end

      if attributes.key?(:'sum_txs_in_forever_gaming')
        self.sum_txs_in_forever_gaming = attributes[:'sum_txs_in_forever_gaming']
      end

      if attributes.key?(:'sum_txs_in_forever_gambling')
        self.sum_txs_in_forever_gambling = attributes[:'sum_txs_in_forever_gambling']
      end

      if attributes.key?(:'sum_txs_in_365_onchain')
        self.sum_txs_in_365_onchain = attributes[:'sum_txs_in_365_onchain']
      end

      if attributes.key?(:'sum_txs_in_365_nft')
        self.sum_txs_in_365_nft = attributes[:'sum_txs_in_365_nft']
      end

      if attributes.key?(:'sum_txs_in_365_gaming')
        self.sum_txs_in_365_gaming = attributes[:'sum_txs_in_365_gaming']
      end

      if attributes.key?(:'sum_txs_in_365_gambling')
        self.sum_txs_in_365_gambling = attributes[:'sum_txs_in_365_gambling']
      end

      if attributes.key?(:'sum_txs_in_31_60_onchain')
        self.sum_txs_in_31_60_onchain = attributes[:'sum_txs_in_31_60_onchain']
      end

      if attributes.key?(:'sum_txs_in_31_60_nft')
        self.sum_txs_in_31_60_nft = attributes[:'sum_txs_in_31_60_nft']
      end

      if attributes.key?(:'sum_txs_in_31_60_gaming')
        self.sum_txs_in_31_60_gaming = attributes[:'sum_txs_in_31_60_gaming']
      end

      if attributes.key?(:'sum_txs_in_31_60_gambling')
        self.sum_txs_in_31_60_gambling = attributes[:'sum_txs_in_31_60_gambling']
      end

      if attributes.key?(:'sum_txs_in_30_onchain')
        self.sum_txs_in_30_onchain = attributes[:'sum_txs_in_30_onchain']
      end

      if attributes.key?(:'sum_txs_in_30_nft')
        self.sum_txs_in_30_nft = attributes[:'sum_txs_in_30_nft']
      end

      if attributes.key?(:'sum_txs_in_30_gaming')
        self.sum_txs_in_30_gaming = attributes[:'sum_txs_in_30_gaming']
      end

      if attributes.key?(:'sum_txs_in_30_gambling')
        self.sum_txs_in_30_gambling = attributes[:'sum_txs_in_30_gambling']
      end

      if attributes.key?(:'sum_txs_in_7_onchain')
        self.sum_txs_in_7_onchain = attributes[:'sum_txs_in_7_onchain']
      end

      if attributes.key?(:'sum_txs_in_7_nft')
        self.sum_txs_in_7_nft = attributes[:'sum_txs_in_7_nft']
      end

      if attributes.key?(:'sum_txs_in_7_gaming')
        self.sum_txs_in_7_gaming = attributes[:'sum_txs_in_7_gaming']
      end

      if attributes.key?(:'sum_txs_in_7_gambling')
        self.sum_txs_in_7_gambling = attributes[:'sum_txs_in_7_gambling']
      end

      if attributes.key?(:'sum_txs_out_forever_onchain')
        self.sum_txs_out_forever_onchain = attributes[:'sum_txs_out_forever_onchain']
      end

      if attributes.key?(:'sum_txs_out_forever_nft')
        self.sum_txs_out_forever_nft = attributes[:'sum_txs_out_forever_nft']
      end

      if attributes.key?(:'sum_txs_out_forever_gaming')
        self.sum_txs_out_forever_gaming = attributes[:'sum_txs_out_forever_gaming']
      end

      if attributes.key?(:'sum_txs_out_forever_gambling')
        self.sum_txs_out_forever_gambling = attributes[:'sum_txs_out_forever_gambling']
      end

      if attributes.key?(:'sum_txs_out_365_onchain')
        self.sum_txs_out_365_onchain = attributes[:'sum_txs_out_365_onchain']
      end

      if attributes.key?(:'sum_txs_out_365_nft')
        self.sum_txs_out_365_nft = attributes[:'sum_txs_out_365_nft']
      end

      if attributes.key?(:'sum_txs_out_365_gaming')
        self.sum_txs_out_365_gaming = attributes[:'sum_txs_out_365_gaming']
      end

      if attributes.key?(:'sum_txs_out_365_gambling')
        self.sum_txs_out_365_gambling = attributes[:'sum_txs_out_365_gambling']
      end

      if attributes.key?(:'sum_txs_out_31_60_onchain')
        self.sum_txs_out_31_60_onchain = attributes[:'sum_txs_out_31_60_onchain']
      end

      if attributes.key?(:'sum_txs_out_31_60_nft')
        self.sum_txs_out_31_60_nft = attributes[:'sum_txs_out_31_60_nft']
      end

      if attributes.key?(:'sum_txs_out_31_60_gaming')
        self.sum_txs_out_31_60_gaming = attributes[:'sum_txs_out_31_60_gaming']
      end

      if attributes.key?(:'sum_txs_out_31_60_gambling')
        self.sum_txs_out_31_60_gambling = attributes[:'sum_txs_out_31_60_gambling']
      end

      if attributes.key?(:'sum_txs_out_30_onchain')
        self.sum_txs_out_30_onchain = attributes[:'sum_txs_out_30_onchain']
      end

      if attributes.key?(:'sum_txs_out_30_nft')
        self.sum_txs_out_30_nft = attributes[:'sum_txs_out_30_nft']
      end

      if attributes.key?(:'sum_txs_out_30_gaming')
        self.sum_txs_out_30_gaming = attributes[:'sum_txs_out_30_gaming']
      end

      if attributes.key?(:'sum_txs_out_30_gambling')
        self.sum_txs_out_30_gambling = attributes[:'sum_txs_out_30_gambling']
      end

      if attributes.key?(:'sum_txs_out_7_onchain')
        self.sum_txs_out_7_onchain = attributes[:'sum_txs_out_7_onchain']
      end

      if attributes.key?(:'sum_txs_out_7_nft')
        self.sum_txs_out_7_nft = attributes[:'sum_txs_out_7_nft']
      end

      if attributes.key?(:'sum_txs_out_7_gaming')
        self.sum_txs_out_7_gaming = attributes[:'sum_txs_out_7_gaming']
      end

      if attributes.key?(:'sum_txs_out_7_gambling')
        self.sum_txs_out_7_gambling = attributes[:'sum_txs_out_7_gambling']
      end

      if attributes.key?(:'max_balance_forever_onchain')
        self.max_balance_forever_onchain = attributes[:'max_balance_forever_onchain']
      end

      if attributes.key?(:'max_balance_forever_nft')
        self.max_balance_forever_nft = attributes[:'max_balance_forever_nft']
      end

      if attributes.key?(:'max_balance_forever_gaming')
        self.max_balance_forever_gaming = attributes[:'max_balance_forever_gaming']
      end

      if attributes.key?(:'max_balance_forever_gambling')
        self.max_balance_forever_gambling = attributes[:'max_balance_forever_gambling']
      end

      if attributes.key?(:'max_balance_365_onchain')
        self.max_balance_365_onchain = attributes[:'max_balance_365_onchain']
      end

      if attributes.key?(:'max_balance_365_nft')
        self.max_balance_365_nft = attributes[:'max_balance_365_nft']
      end

      if attributes.key?(:'max_balance_365_gaming')
        self.max_balance_365_gaming = attributes[:'max_balance_365_gaming']
      end

      if attributes.key?(:'max_balance_365_gambling')
        self.max_balance_365_gambling = attributes[:'max_balance_365_gambling']
      end

      if attributes.key?(:'max_balance_31_60_onchain')
        self.max_balance_31_60_onchain = attributes[:'max_balance_31_60_onchain']
      end

      if attributes.key?(:'max_balance_31_60_nft')
        self.max_balance_31_60_nft = attributes[:'max_balance_31_60_nft']
      end

      if attributes.key?(:'max_balance_31_60_gaming')
        self.max_balance_31_60_gaming = attributes[:'max_balance_31_60_gaming']
      end

      if attributes.key?(:'max_balance_31_60_gambling')
        self.max_balance_31_60_gambling = attributes[:'max_balance_31_60_gambling']
      end

      if attributes.key?(:'max_balance_30_onchain')
        self.max_balance_30_onchain = attributes[:'max_balance_30_onchain']
      end

      if attributes.key?(:'max_balance_30_nft')
        self.max_balance_30_nft = attributes[:'max_balance_30_nft']
      end

      if attributes.key?(:'max_balance_30_gaming')
        self.max_balance_30_gaming = attributes[:'max_balance_30_gaming']
      end

      if attributes.key?(:'max_balance_30_gambling')
        self.max_balance_30_gambling = attributes[:'max_balance_30_gambling']
      end

      if attributes.key?(:'max_balance_7_onchain')
        self.max_balance_7_onchain = attributes[:'max_balance_7_onchain']
      end

      if attributes.key?(:'max_balance_7_nft')
        self.max_balance_7_nft = attributes[:'max_balance_7_nft']
      end

      if attributes.key?(:'max_balance_7_gaming')
        self.max_balance_7_gaming = attributes[:'max_balance_7_gaming']
      end

      if attributes.key?(:'max_balance_7_gambling')
        self.max_balance_7_gambling = attributes[:'max_balance_7_gambling']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sum_txs_all_forever_onchain == o.sum_txs_all_forever_onchain &&
          sum_txs_all_forever_nft == o.sum_txs_all_forever_nft &&
          sum_txs_all_forever_gaming == o.sum_txs_all_forever_gaming &&
          sum_txs_all_forever_gambling == o.sum_txs_all_forever_gambling &&
          sum_txs_all_365_onchain == o.sum_txs_all_365_onchain &&
          sum_txs_all_365_nft == o.sum_txs_all_365_nft &&
          sum_txs_all_365_gaming == o.sum_txs_all_365_gaming &&
          sum_txs_all_365_gambling == o.sum_txs_all_365_gambling &&
          sum_txs_all_31_60_onchain == o.sum_txs_all_31_60_onchain &&
          sum_txs_all_31_60_nft == o.sum_txs_all_31_60_nft &&
          sum_txs_all_31_60_gaming == o.sum_txs_all_31_60_gaming &&
          sum_txs_all_31_60_gambling == o.sum_txs_all_31_60_gambling &&
          sum_txs_all_30_onchain == o.sum_txs_all_30_onchain &&
          sum_txs_all_30_nft == o.sum_txs_all_30_nft &&
          sum_txs_all_30_gaming == o.sum_txs_all_30_gaming &&
          sum_txs_all_30_gambling == o.sum_txs_all_30_gambling &&
          sum_txs_all_7_onchain == o.sum_txs_all_7_onchain &&
          sum_txs_all_7_nft == o.sum_txs_all_7_nft &&
          sum_txs_all_7_gaming == o.sum_txs_all_7_gaming &&
          sum_txs_all_7_gambling == o.sum_txs_all_7_gambling &&
          sum_txs_in_forever_onchain == o.sum_txs_in_forever_onchain &&
          sum_txs_in_forever_nft == o.sum_txs_in_forever_nft &&
          sum_txs_in_forever_gaming == o.sum_txs_in_forever_gaming &&
          sum_txs_in_forever_gambling == o.sum_txs_in_forever_gambling &&
          sum_txs_in_365_onchain == o.sum_txs_in_365_onchain &&
          sum_txs_in_365_nft == o.sum_txs_in_365_nft &&
          sum_txs_in_365_gaming == o.sum_txs_in_365_gaming &&
          sum_txs_in_365_gambling == o.sum_txs_in_365_gambling &&
          sum_txs_in_31_60_onchain == o.sum_txs_in_31_60_onchain &&
          sum_txs_in_31_60_nft == o.sum_txs_in_31_60_nft &&
          sum_txs_in_31_60_gaming == o.sum_txs_in_31_60_gaming &&
          sum_txs_in_31_60_gambling == o.sum_txs_in_31_60_gambling &&
          sum_txs_in_30_onchain == o.sum_txs_in_30_onchain &&
          sum_txs_in_30_nft == o.sum_txs_in_30_nft &&
          sum_txs_in_30_gaming == o.sum_txs_in_30_gaming &&
          sum_txs_in_30_gambling == o.sum_txs_in_30_gambling &&
          sum_txs_in_7_onchain == o.sum_txs_in_7_onchain &&
          sum_txs_in_7_nft == o.sum_txs_in_7_nft &&
          sum_txs_in_7_gaming == o.sum_txs_in_7_gaming &&
          sum_txs_in_7_gambling == o.sum_txs_in_7_gambling &&
          sum_txs_out_forever_onchain == o.sum_txs_out_forever_onchain &&
          sum_txs_out_forever_nft == o.sum_txs_out_forever_nft &&
          sum_txs_out_forever_gaming == o.sum_txs_out_forever_gaming &&
          sum_txs_out_forever_gambling == o.sum_txs_out_forever_gambling &&
          sum_txs_out_365_onchain == o.sum_txs_out_365_onchain &&
          sum_txs_out_365_nft == o.sum_txs_out_365_nft &&
          sum_txs_out_365_gaming == o.sum_txs_out_365_gaming &&
          sum_txs_out_365_gambling == o.sum_txs_out_365_gambling &&
          sum_txs_out_31_60_onchain == o.sum_txs_out_31_60_onchain &&
          sum_txs_out_31_60_nft == o.sum_txs_out_31_60_nft &&
          sum_txs_out_31_60_gaming == o.sum_txs_out_31_60_gaming &&
          sum_txs_out_31_60_gambling == o.sum_txs_out_31_60_gambling &&
          sum_txs_out_30_onchain == o.sum_txs_out_30_onchain &&
          sum_txs_out_30_nft == o.sum_txs_out_30_nft &&
          sum_txs_out_30_gaming == o.sum_txs_out_30_gaming &&
          sum_txs_out_30_gambling == o.sum_txs_out_30_gambling &&
          sum_txs_out_7_onchain == o.sum_txs_out_7_onchain &&
          sum_txs_out_7_nft == o.sum_txs_out_7_nft &&
          sum_txs_out_7_gaming == o.sum_txs_out_7_gaming &&
          sum_txs_out_7_gambling == o.sum_txs_out_7_gambling &&
          max_balance_forever_onchain == o.max_balance_forever_onchain &&
          max_balance_forever_nft == o.max_balance_forever_nft &&
          max_balance_forever_gaming == o.max_balance_forever_gaming &&
          max_balance_forever_gambling == o.max_balance_forever_gambling &&
          max_balance_365_onchain == o.max_balance_365_onchain &&
          max_balance_365_nft == o.max_balance_365_nft &&
          max_balance_365_gaming == o.max_balance_365_gaming &&
          max_balance_365_gambling == o.max_balance_365_gambling &&
          max_balance_31_60_onchain == o.max_balance_31_60_onchain &&
          max_balance_31_60_nft == o.max_balance_31_60_nft &&
          max_balance_31_60_gaming == o.max_balance_31_60_gaming &&
          max_balance_31_60_gambling == o.max_balance_31_60_gambling &&
          max_balance_30_onchain == o.max_balance_30_onchain &&
          max_balance_30_nft == o.max_balance_30_nft &&
          max_balance_30_gaming == o.max_balance_30_gaming &&
          max_balance_30_gambling == o.max_balance_30_gambling &&
          max_balance_7_onchain == o.max_balance_7_onchain &&
          max_balance_7_nft == o.max_balance_7_nft &&
          max_balance_7_gaming == o.max_balance_7_gaming &&
          max_balance_7_gambling == o.max_balance_7_gambling
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sum_txs_all_forever_onchain, sum_txs_all_forever_nft, sum_txs_all_forever_gaming, sum_txs_all_forever_gambling, sum_txs_all_365_onchain, sum_txs_all_365_nft, sum_txs_all_365_gaming, sum_txs_all_365_gambling, sum_txs_all_31_60_onchain, sum_txs_all_31_60_nft, sum_txs_all_31_60_gaming, sum_txs_all_31_60_gambling, sum_txs_all_30_onchain, sum_txs_all_30_nft, sum_txs_all_30_gaming, sum_txs_all_30_gambling, sum_txs_all_7_onchain, sum_txs_all_7_nft, sum_txs_all_7_gaming, sum_txs_all_7_gambling, sum_txs_in_forever_onchain, sum_txs_in_forever_nft, sum_txs_in_forever_gaming, sum_txs_in_forever_gambling, sum_txs_in_365_onchain, sum_txs_in_365_nft, sum_txs_in_365_gaming, sum_txs_in_365_gambling, sum_txs_in_31_60_onchain, sum_txs_in_31_60_nft, sum_txs_in_31_60_gaming, sum_txs_in_31_60_gambling, sum_txs_in_30_onchain, sum_txs_in_30_nft, sum_txs_in_30_gaming, sum_txs_in_30_gambling, sum_txs_in_7_onchain, sum_txs_in_7_nft, sum_txs_in_7_gaming, sum_txs_in_7_gambling, sum_txs_out_forever_onchain, sum_txs_out_forever_nft, sum_txs_out_forever_gaming, sum_txs_out_forever_gambling, sum_txs_out_365_onchain, sum_txs_out_365_nft, sum_txs_out_365_gaming, sum_txs_out_365_gambling, sum_txs_out_31_60_onchain, sum_txs_out_31_60_nft, sum_txs_out_31_60_gaming, sum_txs_out_31_60_gambling, sum_txs_out_30_onchain, sum_txs_out_30_nft, sum_txs_out_30_gaming, sum_txs_out_30_gambling, sum_txs_out_7_onchain, sum_txs_out_7_nft, sum_txs_out_7_gaming, sum_txs_out_7_gambling, max_balance_forever_onchain, max_balance_forever_nft, max_balance_forever_gaming, max_balance_forever_gambling, max_balance_365_onchain, max_balance_365_nft, max_balance_365_gaming, max_balance_365_gambling, max_balance_31_60_onchain, max_balance_31_60_nft, max_balance_31_60_gaming, max_balance_31_60_gambling, max_balance_30_onchain, max_balance_30_nft, max_balance_30_gaming, max_balance_30_gambling, max_balance_7_onchain, max_balance_7_nft, max_balance_7_gaming, max_balance_7_gambling].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Blockmate.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
