=begin
#Blockmate

#Blockmate API OpenAPI documentation

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

# Common files
require 'blockmate/api_client'
require 'blockmate/api_error'
require 'blockmate/version'
require 'blockmate/configuration'

# Models
require 'blockmate/models/account'
require 'blockmate/models/account_provider'
require 'blockmate/models/account_provider_hint'
require 'blockmate/models/account_provider_hint_fields'
require 'blockmate/models/address_risk_report'
require 'blockmate/models/address_risk_report_details'
require 'blockmate/models/amount'
require 'blockmate/models/auth_user200_response'
require 'blockmate/models/balance200_response'
require 'blockmate/models/balance_response'
require 'blockmate/models/balance_response_accounts_inner'
require 'blockmate/models/balance_response_accounts_inner_state'
require 'blockmate/models/connect_account200_response'
require 'blockmate/models/connect_account400_response'
require 'blockmate/models/connect_account405_response'
require 'blockmate/models/connect_account_request'
require 'blockmate/models/create_user_request'
require 'blockmate/models/delete_account404_response'
require 'blockmate/models/delete_user200_response'
require 'blockmate/models/delete_user404_response'
require 'blockmate/models/exchange_rate'
require 'blockmate/models/get_account_hint200_response'
require 'blockmate/models/get_account_hint200_response_fields'
require 'blockmate/models/get_account_hint403_response'
require 'blockmate/models/get_account_hint404_response'
require 'blockmate/models/get_address_from_domain200_response'
require 'blockmate/models/get_address_name_info_single200_response'
require 'blockmate/models/get_address_risk_score200_response'
require 'blockmate/models/get_analytics200_response'
require 'blockmate/models/get_analytics200_response_value'
require 'blockmate/models/get_domain_from_address200_response'
require 'blockmate/models/get_domain_from_address200_response_metadata'
require 'blockmate/models/get_domain_from_address200_response_metadata_attributes_inner'
require 'blockmate/models/get_domain_from_address200_response_metadata_attributes_inner_value'
require 'blockmate/models/get_transaction_risk_score200_response'
require 'blockmate/models/get_user404_response'
require 'blockmate/models/metadata'
require 'blockmate/models/metadata_attributes_inner'
require 'blockmate/models/movement'
require 'blockmate/models/nft_metadata200_response_value'
require 'blockmate/models/nft_contract_metadata'
require 'blockmate/models/nft_id'
require 'blockmate/models/nft_id_token_metadata'
require 'blockmate/models/nft_media'
require 'blockmate/models/nft_spam_info'
require 'blockmate/models/nft_token_uri'
require 'blockmate/models/owned_nft'
require 'blockmate/models/owned_nft_contract'
require 'blockmate/models/owned_nft_media'
require 'blockmate/models/risk_report_category'
require 'blockmate/models/transaction'
require 'blockmate/models/transaction_risk_report'
require 'blockmate/models/transactions200_response'
require 'blockmate/models/transactions200_response_accounts_inner'
require 'blockmate/models/user'
require 'blockmate/models/user_api_authenticate_project200_response'
require 'blockmate/models/user_api_authenticate_project400_response'
require 'blockmate/models/user_api_authenticate_project401_response'

# APIs
require 'blockmate/api/account_provider_info_api'
require 'blockmate/api/address_name_and_category_info_api'
require 'blockmate/api/aggregated_info_api'
require 'blockmate/api/analytics_api'
require 'blockmate/api/authentication_api'
require 'blockmate/api/ens_api'
require 'blockmate/api/exchange_rate_info_api'
require 'blockmate/api/risk_info_api'
require 'blockmate/api/user_management_api'

module Blockmate
  class << self
    # Customize default settings for the SDK using block.
    #   Blockmate.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
